services:
  server:
    build: ./server
    command: >
      sh -c "gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    # env_file:
    #   - ./server/.env
  web:
    build: ./web
    volumes:
      - ~/web:/usr/src/web-app
    env_file:
      - ./web/.env
    ports:
      - 3000:3000
volumes: 
  pgdata:
